# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MOTE
email: mail.moteorganizacion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Mote organization new web and repository
baseurl: "/Maizeed" # the subpath of your site, e.g. /blog
url: "https://moteorg.github.io/Maizeed/" # the base hostname & protocol for your site
twitter_username: MOTEorg
github_username:  MOTEorg

# Build settings
theme: jekyll-theme-tactile
highlighter: rouge
markdown: kramdown
