# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MoteOrg
email: mail.moteorganizacion@gmail.com
description: Moteorg Official Web > # this means to ignore newlines until "baseurl:"
 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moteorg.github.io" # the base hostname & protocol for your site
twitter_username: MOTEorg
github_username:  MOTEorg

# Tracker
analytics: # Google Analytics

# Build settings
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 6
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]